version: '3'
services:
    php:
#        image: quickfly/phpfly:8.0.28-fpm-2
        image: mhzuhe/php-fpm:8.2
        restart: always
        networks:
            - internal
#            - web
        volumes:
            - ./:/var/www/html
            - ./deploy/supervisor:/etc/supervisor/conf.d

        environment:
            - APP_ENV=prod
#            - APP_ENV=$APP_ENV
            - LANG=en_US.UTF-8
#        command: [ "bash", "-c", "docker-php-ext-install pdo_mysql mysqli && docker-php-ext-enable pdo_mysql mysqli && docker-php-ext-install opcache gd && docker-php-ext-enable opcache gd" ]

    redis:
        image: "redis:7.0.2"
        restart: always
        networks:
            - internal
    nginx:
        image: nginx:1.22.0
        restart: always
        networks:
#            - web
            - internal
#        expose:
#            - 80
        ports:
            - "6111:80"
        depends_on:
            - "php"
        environment:
#            - NGINX_HOST=$NGINX_HOST
            - NGINX_PORT=80
            # virtual_* for nginx-proxy
#            - VIRTUAL_HOST=$NGINX_HOST
#            - VIRTUAL_PORT=80
        volumes:
            - ./deploy/nginx/conf.d/erp.conf:/etc/nginx/conf.d/erp.conf
    mysql:
        image: mysql:8.0.23
        # command: --default-authentication-plugin=mysql_native_password
        platform: linux/x86_64

        environment:
            MYSQL_DATABASE: erp-php
            MYSQL_ROOT_PASSWORD: Yzx1521!hui
            MYSQL_USER: erp_php
            MYSQL_PASSWORD: Yzx1521!hui
            MYSQL_TCP_PORT: 3306
            MYSQL_ROOT_HOST: '%'
        healthcheck:
            test: "/usr/bin/mysql --user=erp_php --password=Yzx1521!hui --execute \"SHOW DATABASES;\""
            interval: 5s
            timeout: 2s
            retries: 100
        networks:
            - internal
        volumes:
            - ./deploy/mysql/data:/var/lib/mysql
            - ./deploy/mysql/conf/my.cnf:/etc/mysql/my.cnf
            - ./deploy/mysql/log:/var/log/mysql
            - ./deploy/mysql/files:/var/lib/mysql-files
#            - ./mysql/jsh_erp.sql:/docker-entrypoint-initdb.d/jsh_erp.sql
networks:
    internal:
        external: false
#    web:
#        external: true
